// src/components/AssetRackPlacement.tsx
import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Empty, ErrorNotice, Field, optional } from './ui'
import { api } from '../services/api'
import type { AssetDetailModel, Rack, RackOrientation } from '../types/api'

type Placement = AssetDetailModel['rackPlacements'][number]
export default function AssetRackPlacement({ asset, onRefresh }: { asset: AssetDetailModel; onRefresh: () => Promise<void> }) {
  const [racks, setRacks] = useState<Rack[]>([])
  const [editing, setEditing] = useState<Placement | 'new' | null>(null)
  const [rackId, setRackId] = useState('')
  const [startUnit, setStartUnit] = useState(1)
  const [heightUnits, setHeightUnits] = useState(1)
  const [orientation, setOrientation] = useState<RackOrientation>('front')
  const [notes, setNotes] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { let active = true; void api.racks.list().then(rows => { if (active) setRacks(rows) }).catch(cause => { if (active) setError(cause.message) }); return () => { active = false } }, [])
  function open(row: Placement | 'new') { setEditing(row); setRackId(row === 'new' ? racks[0]?.id || '' : row.rackId); setStartUnit(row === 'new' ? racks[0]?.startingUnit || 1 : row.startUnit); setHeightUnits(row === 'new' ? 1 : row.heightUnits); setOrientation(row === 'new' ? 'front' : row.orientation); setNotes(row === 'new' ? '' : row.notes || '') }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const input = { assetId: asset.id, startUnit, heightUnits, orientation, notes: optional(notes) }; if (editing === 'new') await api.racks.placements.create(rackId, input); else await api.racks.placements.update((editing as Placement).rackId, (editing as Placement).id, input); await onRefresh(); setEditing(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save placement.') } finally { setBusy(false) } }
  async function remove(row: Placement) { if (!window.confirm(`Remove ${asset.name} from ${row.rack.name}?`)) return; setError(null); try { await api.racks.placements.delete(row.rackId, row.id); await onRefresh(); setEditing(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not remove placement.') } }
  const selectedRack = racks.find(row => row.id === rackId)
  return <section className="panel"><div className="section-heading"><h2>Rack / location</h2><button className="small" disabled={!racks.length} onClick={() => open('new')}>+ Place in rack</button></div><ErrorNotice error={error} /><p>Location: {asset.location?.name || 'Unassigned'}</p>{asset.rackPlacements.length ? <div className="chip-list">{asset.rackPlacements.map(row => <div className="chip" key={row.id}><Link to={`/racks/${row.rackId}`}>{row.rack.name}</Link><small>{row.orientation} · U{row.startUnit}–{row.startUnit + row.heightUnits - 1} · {row.heightUnits}U</small><div className="inline"><button className="secondary small" onClick={() => open(row)}>Edit</button><button className="danger-outline small" onClick={() => void remove(row)}>Remove</button></div></div>)}</div> : <Empty>Not installed in a rack.</Empty>}
    {editing && <form className="form-grid subpanel" onSubmit={e => void save(e)}><h3 className="full">{editing === 'new' ? 'Place asset' : 'Edit placement'}</h3><Field label="Rack"><select disabled={editing !== 'new'} value={rackId} onChange={e => { setRackId(e.target.value); setStartUnit(racks.find(row => row.id === e.target.value)?.startingUnit || 1) }}>{racks.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Orientation"><select value={orientation} onChange={e => setOrientation(e.target.value as RackOrientation)}><option value="front">Front</option><option value="rear">Rear</option></select></Field><Field label="Starting U"><input type="number" min={selectedRack?.startingUnit || 1} max={selectedRack ? selectedRack.startingUnit + selectedRack.totalUnits - 1 : undefined} required value={startUnit} onChange={e => setStartUnit(Number(e.target.value))} /></Field><Field label="Height U"><input type="number" min="1" required value={heightUnits} onChange={e => setHeightUnits(Number(e.target.value))} /></Field><div className="full"><Field label="Notes"><input value={notes} onChange={e => setNotes(e.target.value)} /></Field></div><div className="form-actions"><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancel</button><button disabled={busy || !rackId}>Save placement</button></div></form>}
  </section>
}

// app/components/AssetRackPlacement.vue
<script setup lang="ts">
import { api } from '../../services/api'
import type { AssetDetailModel, PlacementFields, Rack, RackOrientation } from '../../types/api'
const props = defineProps<{ asset: AssetDetailModel }>()
const emit = defineEmits<{ refresh: [] }>()
const racks = ref<Rack[]>([])
const editing = ref(false)
const busy = ref(false)
const error = ref<string | null>(null)
const form = reactive({ rackId: '', startUnit: 1, orientation: 'front' as RackOrientation, notes: '' })
onMounted(async () => { try { racks.value = await api.racks.list() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not load racks.' } })
const rackOptions = computed(() => racks.value.map(row => ({ label: row.name, value: row.id })))
const selectedRack = computed(() => racks.value.find(row => row.id === form.rackId))
function open(placement?: AssetDetailModel['rackPlacements'][number]) { Object.assign(form, { rackId: placement?.rackId || racks.value[0]?.id || '', startUnit: placement?.startUnit || 1, orientation: placement?.orientation || 'front', notes: placement?.notes || '' }); editing.value = true; selected.value = placement || null }
const selected = ref<AssetDetailModel['rackPlacements'][number] | null>(null)
async function save() { busy.value = true; error.value = null; try { const input: PlacementFields = { assetId: props.asset.id, startUnit: Number(form.startUnit), orientation: form.orientation, notes: form.notes.trim() || null }; if (selected.value) await api.racks.placements.update(form.rackId, selected.value.id, input); else await api.racks.placements.create(form.rackId, input); editing.value = false; emit('refresh') } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not save placement.' } finally { busy.value = false } }
async function remove(row: AssetDetailModel['rackPlacements'][number]) { if (!window.confirm(`Remove ${props.asset.name} from ${row.rack.name}?`)) return; try { error.value = null; await api.racks.placements.delete(row.rackId, row.id); editing.value = false; emit('refresh') } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not remove placement.' } }
</script>
<template>
  <section class="panel"><div class="section-heading"><h2 class="text-lg font-semibold">Rack / location</h2><UButton size="sm" icon="i-lucide-plus" :disabled="!racks.length" @click="open()">Place in rack</UButton></div><p class="muted mb-3">Location: {{ asset.location?.name || 'No location' }} · Device height: {{ asset.rackUnits }}U</p><div v-if="asset.rackPlacements.length" class="table-scroll"><table class="data-table"><thead><tr><th>Rack</th><th>Position</th><th>Height</th><th>Side</th><th>Actions</th></tr></thead><tbody><tr v-for="row in asset.rackPlacements" :key="row.id"><td><NuxtLink :to="`/racks/${row.rackId}`">{{ row.rack.name }}</NuxtLink></td><td>{{ row.startUnit }}U</td><td>{{ asset.rackUnits }}U</td><td>{{ row.orientation }}</td><td><div class="actions"><UButton size="xs" variant="outline" @click="open(row)">Edit</UButton><UButton size="xs" variant="outline" color="error" @click="remove(row)">Remove</UButton></div></td></tr></tbody></table></div><p v-else class="muted">No rack placement.</p><UAlert v-if="error" color="error" :title="error" class="mt-3" /></section>
  <section v-if="editing" class="panel"><h2 class="mb-4 text-lg font-semibold">{{ selected ? 'Edit placement' : 'Place asset' }}</h2><form class="form-grid" @submit.prevent="save"><UFormField label="Rack" required><USelect v-model="form.rackId" :items="rackOptions" :disabled="!!selected" class="w-full" /></UFormField><UFormField label="Side"><USelect v-model="form.orientation" :items="[{ label: 'Front', value: 'front' }, { label: 'Rear', value: 'rear' }]" class="w-full" /></UFormField><UFormField label="Starting U"><UInput v-model="form.startUnit" type="number" :min="selectedRack?.startingUnit || 1" :max="selectedRack ? selectedRack.startingUnit + selectedRack.totalUnits - 1 : undefined" required class="w-full" /></UFormField><UFormField label="Notes"><UInput v-model="form.notes" class="w-full" /></UFormField><div class="form-actions full"><UButton type="button" variant="outline" color="neutral" @click="editing = false">Cancel</UButton><UButton type="submit" :loading="busy" :disabled="!form.rackId">Save placement</UButton></div></form></section>
</template>
