// src/components/ItemForm.tsx
import { useState, type FormEvent } from 'react'
import { itemStatuses, type CreateProjectItem, type ItemStatus, type ItemType, type ProjectItem, type UpdateProjectItem } from '../types/api'
import { amount, ErrorNotice, Field, optional } from './ui'

function localDateTime(value: string | null | undefined) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
function iso(value: string) { return value ? new Date(value).toISOString() : null }

export default function ItemForm({ item, onSave, onCancel }: { item?: ProjectItem; onSave: (input: CreateProjectItem | UpdateProjectItem) => Promise<void>; onCancel: () => void }) {
  const [type, setType] = useState<ItemType>(item?.type ?? 'work')
  const [title, setTitle] = useState(item?.title ?? '')
  const [description, setDescription] = useState(item?.description ?? '')
  const [status, setStatus] = useState<ItemStatus>(item?.status ?? 'planned')
  const [targetDate, setTargetDate] = useState(item?.targetDate ?? '')
  const [vendor, setVendor] = useState(item?.vendor ?? '')
  const [url, setUrl] = useState(item?.url ?? '')
  const [estimatedCost, setEstimatedCost] = useState(item?.estimatedCost?.toString() ?? '')
  const [actualCost, setActualCost] = useState(item?.actualCost?.toString() ?? '')
  const [shippingCost, setShippingCost] = useState(item?.shippingCost?.toString() ?? '')
  const [orderedAt, setOrderedAt] = useState(localDateTime(item?.orderedAt))
  const [receivedAt, setReceivedAt] = useState(localDateTime(item?.receivedAt))
  const [completedAt, setCompletedAt] = useState(localDateTime(item?.completedAt))
  const [sortOrder, setSortOrder] = useState(item?.sortOrder?.toString() ?? '0')
  const [notes, setNotes] = useState(item?.notes ?? '')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  async function submit(event: FormEvent) {
    event.preventDefault()
    if (!title.trim()) { setError('Title is required.'); return }
    const input = { type, title: title.trim(), description: optional(description), status, targetDate: optional(targetDate), vendor: optional(vendor), url: optional(url), estimatedCost: amount(estimatedCost), actualCost: amount(actualCost), shippingCost: amount(shippingCost), orderedAt: iso(orderedAt), receivedAt: iso(receivedAt), completedAt: iso(completedAt), notes: optional(notes), sortOrder: Number(sortOrder) }
    setBusy(true); setError(null)
    try { await onSave(input) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save item.') } finally { setBusy(false) }
  }
  return <form className="form-grid" onSubmit={submit}><ErrorNotice error={error} />
    <Field label="Type *"><select value={type} onChange={e => setType(e.target.value as ItemType)}><option value="work">Work</option><option value="purchase">Purchase</option></select></Field>
    <Field label="Title *"><input required value={title} onChange={e => setTitle(e.target.value)} /></Field>
    <Field label="Status"><select value={status} onChange={e => setStatus(e.target.value as ItemStatus)}>{itemStatuses.map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></Field>
    <Field label="Target date"><input type="date" value={targetDate} onChange={e => setTargetDate(e.target.value)} /></Field>
    <Field label="Sort order"><input type="number" step="0.01" min="-99999999.99" max="99999999.99" required value={sortOrder} onChange={e => setSortOrder(e.target.value)} /></Field>
    <Field label="Description"><textarea rows={3} value={description} onChange={e => setDescription(e.target.value)} /></Field>
    {type === 'purchase' && <><Field label="Vendor"><input value={vendor} onChange={e => setVendor(e.target.value)} /></Field><Field label="URL"><input type="url" value={url} onChange={e => setUrl(e.target.value)} /></Field>
      <Field label="Estimated cost"><input type="number" min="0" max="9999999999.99" step="0.01" value={estimatedCost} onChange={e => setEstimatedCost(e.target.value)} /></Field>
      <Field label="Actual cost"><input type="number" min="0" max="9999999999.99" step="0.01" value={actualCost} onChange={e => setActualCost(e.target.value)} /></Field>
      <Field label="Shipping cost"><input type="number" min="0" max="9999999999.99" step="0.01" value={shippingCost} onChange={e => setShippingCost(e.target.value)} /></Field>
      <Field label="Ordered at"><input type="datetime-local" value={orderedAt} onChange={e => setOrderedAt(e.target.value)} /></Field>
      <Field label="Received at"><input type="datetime-local" value={receivedAt} onChange={e => setReceivedAt(e.target.value)} /></Field></>}
    <Field label="Completed at"><input type="datetime-local" value={completedAt} onChange={e => setCompletedAt(e.target.value)} /></Field>
    <Field label="Notes"><textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} /></Field>
    <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button disabled={busy}>{busy ? 'Saving…' : 'Save item'}</button></div>
  </form>
}

// nuxt/app/components/ItemForm.vue
<script setup lang="ts">
import { itemStatuses, type CreateProjectItem, type ItemStatus, type ItemType, type ProjectItem, type UpdateProjectItem } from '../../types/api'
const props = defineProps<{ item?: ProjectItem; onSave: (input: CreateProjectItem | UpdateProjectItem) => Promise<void>; onCancel: () => void }>()
const localDateTime = (value: string | null | undefined) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''
const form = reactive({
  type: (props.item?.type || 'work') as ItemType, title: props.item?.title || '', description: props.item?.description || '',
  status: (props.item?.status || 'planned') as ItemStatus, targetDate: props.item?.targetDate || '', vendor: props.item?.vendor || '',
  url: props.item?.url || '', estimatedCost: props.item?.estimatedCost?.toString() || '', actualCost: props.item?.actualCost?.toString() || '',
  shippingCost: props.item?.shippingCost?.toString() || '', orderedAt: localDateTime(props.item?.orderedAt), receivedAt: localDateTime(props.item?.receivedAt),
  completedAt: localDateTime(props.item?.completedAt), sortOrder: String(props.item?.sortOrder ?? 0), notes: props.item?.notes || '',
})
const busy = ref(false)
const error = ref<string | null>(null)
const typeOptions = [{ label: 'Work', value: 'work' }, { label: 'Purchase', value: 'purchase' }]
const statusOptions = itemStatuses.map(value => ({ label: value.replaceAll('_', ' '), value }))
const optional = (value: string) => value.trim() || null
const amount = (value: string) => value.trim() ? Number(value) : null
const iso = (value: string) => value ? new Date(value).toISOString() : null
async function submit() {
  if (!form.title.trim()) { error.value = 'Title is required.'; return }
  busy.value = true; error.value = null
  try { await props.onSave({ type: form.type, title: form.title.trim(), description: optional(form.description), status: form.status, targetDate: optional(form.targetDate), vendor: optional(form.vendor), url: optional(form.url), estimatedCost: amount(form.estimatedCost), actualCost: amount(form.actualCost), shippingCost: amount(form.shippingCost), orderedAt: iso(form.orderedAt), receivedAt: iso(form.receivedAt), completedAt: iso(form.completedAt), notes: optional(form.notes), sortOrder: Number(form.sortOrder) }) }
  catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not save item.' }
  finally { busy.value = false }
}
</script>

<template>
  <form class="form-grid" @submit.prevent="submit"><UAlert v-if="error" color="error" :title="error" class="full" />
    <UFormField label="Type"><USelect v-model="form.type" :items="typeOptions" class="w-full" /></UFormField>
    <UFormField label="Title" required><UInput v-model="form.title" required class="w-full" /></UFormField>
    <UFormField label="Status"><USelect v-model="form.status" :items="statusOptions" class="w-full" /></UFormField>
    <UFormField label="Target date"><UInput v-model="form.targetDate" type="date" class="w-full" /></UFormField>
    <UFormField label="Sort order"><UInput v-model="form.sortOrder" type="number" step="0.01" class="w-full" /></UFormField>
    <UFormField label="Description"><UTextarea v-model="form.description" :rows="3" class="w-full" /></UFormField>
    <template v-if="form.type === 'purchase'"><UFormField label="Vendor"><UInput v-model="form.vendor" class="w-full" /></UFormField><UFormField label="URL"><UInput v-model="form.url" type="url" class="w-full" /></UFormField><UFormField label="Estimated cost"><UInput v-model="form.estimatedCost" type="number" min="0" step="0.01" class="w-full" /></UFormField><UFormField label="Actual cost"><UInput v-model="form.actualCost" type="number" min="0" step="0.01" class="w-full" /></UFormField><UFormField label="Shipping cost"><UInput v-model="form.shippingCost" type="number" min="0" step="0.01" class="w-full" /></UFormField><UFormField label="Ordered at"><UInput v-model="form.orderedAt" type="datetime-local" class="w-full" /></UFormField><UFormField label="Received at"><UInput v-model="form.receivedAt" type="datetime-local" class="w-full" /></UFormField></template>
    <UFormField label="Completed at"><UInput v-model="form.completedAt" type="datetime-local" class="w-full" /></UFormField>
    <UFormField label="Notes"><UTextarea v-model="form.notes" :rows="3" class="w-full" /></UFormField>
    <div class="form-actions full"><UButton variant="outline" color="neutral" type="button" @click="onCancel">Cancel</UButton><UButton type="submit" :loading="busy">Save item</UButton></div>
  </form>
</template>
