// nuxt/app/components/AssetForm.vue
<script setup lang="ts">
import type { Asset, AssetType, CreateAsset, Location, UpdateAsset, EditableAssetStatus } from '../../types/api'
import { assetStatuses } from '../../types/api'

const props = defineProps<{ asset?: Asset; types: AssetType[]; locations: Location[]; onSave: (input: CreateAsset | UpdateAsset) => Promise<void>; onCancel: () => void }>()
const form = reactive({
  name: props.asset?.name || '', assetTypeId: props.asset?.assetTypeId || props.types[0]?.id || '',
  status: (props.asset?.status === 'archived' ? 'active' : props.asset?.status || 'active') as EditableAssetStatus,
  locationId: props.asset?.locationId || '', hostname: props.asset?.hostname || '', ipAddress: props.asset?.ipAddress || '',
  manufacturer: props.asset?.manufacturer || '', model: props.asset?.model || '', serialNumber: props.asset?.serialNumber || '', notes: props.asset?.notes || '',
})
const busy = ref(false)
const error = ref<string | null>(null)
const typeOptions = computed(() => props.types.map(type => ({ label: type.name, value: type.id })))
const locationOptions = computed(() => [{ label: 'No location', value: '' }, ...props.locations.map(location => ({ label: location.name, value: location.id }))])
const statusOptions = assetStatuses.map(value => ({ label: value, value }))
async function submit() {
  if (!form.name.trim() || !form.assetTypeId) { error.value = 'Name and asset type are required.'; return }
  busy.value = true; error.value = null
  const fields = { name: form.name.trim(), assetTypeId: form.assetTypeId, status: form.status, locationId: form.locationId || null, hostname: form.hostname.trim(), ipAddress: form.ipAddress.trim(), manufacturer: form.manufacturer.trim(), model: form.model.trim(), serialNumber: form.serialNumber.trim(), notes: form.notes.trim() }
  const input: CreateAsset | UpdateAsset = props.asset ? { ...fields, hostname: fields.hostname || null, ipAddress: fields.ipAddress || null, manufacturer: fields.manufacturer || null, model: fields.model || null, serialNumber: fields.serialNumber || null, notes: fields.notes || null } : { ...fields, hostname: fields.hostname || undefined, ipAddress: fields.ipAddress || undefined, manufacturer: fields.manufacturer || undefined, model: fields.model || undefined, serialNumber: fields.serialNumber || undefined, notes: fields.notes || undefined }
  try { await props.onSave(input) } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not save asset.' } finally { busy.value = false }
}
</script>

<template>
  <form class="form-grid" @submit.prevent="submit">
    <UAlert v-if="error" color="error" :title="error" class="full" />
    <UFormField label="Name" required><UInput v-model="form.name" required class="w-full" /></UFormField>
    <UFormField label="Asset type" required><USelect v-model="form.assetTypeId" :items="typeOptions" class="w-full" /></UFormField>
    <UFormField label="Status"><USelect v-model="form.status" :items="statusOptions" class="w-full" /></UFormField>
    <UFormField label="Location"><USelect v-model="form.locationId" :items="locationOptions" class="w-full" /></UFormField>
    <UFormField label="Hostname"><UInput v-model="form.hostname" class="w-full" /></UFormField>
    <UFormField label="Legacy IP address"><UInput v-model="form.ipAddress" placeholder="IPv4 or IPv6" class="w-full" /></UFormField>
    <UFormField label="Manufacturer"><UInput v-model="form.manufacturer" class="w-full" /></UFormField>
    <UFormField label="Model"><UInput v-model="form.model" class="w-full" /></UFormField>
    <UFormField label="Serial number"><UInput v-model="form.serialNumber" class="w-full" /></UFormField>
    <UFormField label="Notes"><UTextarea v-model="form.notes" :rows="3" class="w-full" /></UFormField>
    <div class="form-actions full"><UButton variant="outline" color="neutral" type="button" @click="onCancel">Cancel</UButton><UButton type="submit" :loading="busy" :disabled="!types.length">Save asset</UButton></div>
  </form>
</template>

// src/components/AssetForm.tsx
import { useState, type FormEvent } from 'react'
import { assetStatuses, type Asset, type AssetType, type CreateAsset, type EditableAssetStatus, type Location, type UpdateAsset } from '../types/api'
import { ErrorNotice, Field } from './ui'

export default function AssetForm({ asset, types, locations = [], onSave, onCancel }: { asset?: Asset; types: AssetType[]; locations?: Location[]; onSave: (input: CreateAsset | UpdateAsset) => Promise<void>; onCancel: () => void }) {
  const [name, setName] = useState(asset?.name ?? '')
  const [assetTypeId, setAssetTypeId] = useState(asset?.assetTypeId ?? types[0]?.id ?? '')
  const [status, setStatus] = useState<EditableAssetStatus>(asset?.status === 'archived' ? 'active' : asset?.status ?? 'active')
  const [locationId, setLocationId] = useState(asset?.locationId ?? '')
  const [hostname, setHostname] = useState(asset?.hostname ?? '')
  const [ipAddress, setIpAddress] = useState(asset?.ipAddress ?? '')
  const [manufacturer, setManufacturer] = useState(asset?.manufacturer ?? '')
  const [model, setModel] = useState(asset?.model ?? '')
  const [serialNumber, setSerialNumber] = useState(asset?.serialNumber ?? '')
  const [notes, setNotes] = useState(asset?.notes ?? '')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  async function submit(event: FormEvent) {
    event.preventDefault()
    if (!name.trim() || !assetTypeId) { setError('Name and asset type are required.'); return }
    const fields = { name: name.trim(), assetTypeId, status, locationId: locationId || null, hostname: hostname.trim(), ipAddress: ipAddress.trim(), manufacturer: manufacturer.trim(), model: model.trim(), serialNumber: serialNumber.trim(), notes: notes.trim() }
    const input: CreateAsset | UpdateAsset = asset
      ? { ...fields, hostname: fields.hostname || null, ipAddress: fields.ipAddress || null, manufacturer: fields.manufacturer || null, model: fields.model || null, serialNumber: fields.serialNumber || null, notes: fields.notes || null }
      : fields
    setBusy(true); setError(null)
    try { await onSave(input) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save asset.') } finally { setBusy(false) }
  }
  return <form onSubmit={submit} className="form-grid"><ErrorNotice error={error} />
    <Field label="Name *"><input required value={name} onChange={e => setName(e.target.value)} /></Field>
    <Field label="Asset type *"><select required value={assetTypeId} onChange={e => setAssetTypeId(e.target.value)}><option value="">Select type</option>{types.map(type => <option value={type.id} key={type.id}>{type.name}</option>)}</select></Field>
    <Field label="Status"><select value={status} onChange={e => setStatus(e.target.value as EditableAssetStatus)}>{assetStatuses.map(value => <option key={value} value={value}>{value}</option>)}</select></Field>
    <Field label="Location"><select value={locationId} onChange={e => setLocationId(e.target.value)}><option value="">No location</option>{locations.map(location => <option key={location.id} value={location.id}>{location.name}</option>)}</select></Field>
    <Field label="Hostname"><input value={hostname} onChange={e => setHostname(e.target.value)} /></Field>
    <Field label="IP address"><input value={ipAddress} onChange={e => setIpAddress(e.target.value)} placeholder="IPv4 or IPv6" /></Field>
    <Field label="Manufacturer"><input value={manufacturer} onChange={e => setManufacturer(e.target.value)} /></Field>
    <Field label="Model"><input value={model} onChange={e => setModel(e.target.value)} /></Field>
    <Field label="Serial number"><input value={serialNumber} onChange={e => setSerialNumber(e.target.value)} /></Field>
    <Field label="Notes"><textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} /></Field>
    <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button disabled={busy || !types.length}>{busy ? 'Saving…' : 'Save asset'}</button></div>
  </form>
}
