// nuxt/app/components/ProjectForm.vue
<script setup lang="ts">
import { priorities, projectStatuses, type Asset, type CreateProject, type EditableProjectStatus, type Priority, type Project, type UpdateProject } from '../../types/api'

const props = defineProps<{ project?: Project; assets: Asset[]; onSave: (input: CreateProject | UpdateProject) => Promise<void>; onCancel: () => void }>()
const form = reactive({
  name: props.project?.name || '', description: props.project?.description || '',
  status: (props.project?.status === 'archived' ? 'planned' : props.project?.status || 'idea') as EditableProjectStatus,
  priority: (props.project?.priority || 'normal') as Priority, targetDate: props.project?.targetDate || '',
  estimatedCost: props.project?.estimatedCost?.toString() || '', actualCost: props.project?.actualCost?.toString() || '',
  notes: props.project?.notes || '', assetIds: props.project?.assets.map(asset => asset.id) || [] as string[],
})
const busy = ref(false)
const error = ref<string | null>(null)
const statusOptions = projectStatuses.map(value => ({ label: value.replaceAll('_', ' '), value }))
const priorityOptions = priorities.map(value => ({ label: value, value }))
const optional = (value: string) => value.trim() || null
const amount = (value: string) => value.trim() ? Number(value) : null
function toggle(id: string) { form.assetIds = form.assetIds.includes(id) ? form.assetIds.filter(value => value !== id) : [...form.assetIds, id] }
async function submit() {
  if (!form.name.trim()) { error.value = 'Name is required.'; return }
  busy.value = true; error.value = null
  try { await props.onSave({ name: form.name.trim(), description: optional(form.description), status: form.status, priority: form.priority, targetDate: optional(form.targetDate), estimatedCost: amount(form.estimatedCost), actualCost: amount(form.actualCost), notes: optional(form.notes), assetIds: form.assetIds }) }
  catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not save project.' }
  finally { busy.value = false }
}
</script>

<template>
  <form class="form-grid" @submit.prevent="submit"><UAlert v-if="error" color="error" :title="error" class="full" />
    <UFormField label="Name" required><UInput v-model="form.name" required class="w-full" /></UFormField>
    <UFormField label="Status"><USelect v-model="form.status" :items="statusOptions" class="w-full" /></UFormField>
    <UFormField label="Priority"><USelect v-model="form.priority" :items="priorityOptions" class="w-full" /></UFormField>
    <UFormField label="Target date"><UInput v-model="form.targetDate" type="date" class="w-full" /></UFormField>
    <UFormField label="Estimated cost"><UInput v-model="form.estimatedCost" type="number" min="0" step="0.01" class="w-full" /></UFormField>
    <UFormField label="Actual cost"><UInput v-model="form.actualCost" type="number" min="0" step="0.01" class="w-full" /></UFormField>
    <UFormField label="Description"><UTextarea v-model="form.description" :rows="3" class="w-full" /></UFormField>
    <UFormField label="Notes"><UTextarea v-model="form.notes" :rows="3" class="w-full" /></UFormField>
    <fieldset class="full asset-choices"><legend>Associated assets</legend><p v-if="!assets.length" class="muted">No assets available.</p><label v-for="asset in assets" :key="asset.id"><input type="checkbox" :checked="form.assetIds.includes(asset.id)" @change="toggle(asset.id)" /> <span>{{ asset.name }} <small class="muted">({{ asset.assetType.name }})</small></span></label></fieldset>
    <div class="form-actions full"><UButton variant="outline" color="neutral" type="button" @click="onCancel">Cancel</UButton><UButton type="submit" :loading="busy">Save project</UButton></div>
  </form>
</template>

// src/components/ProjectForm.tsx
import { useState, type FormEvent } from 'react'
import { priorities, projectStatuses, type Asset, type CreateProject, type EditableProjectStatus, type Priority, type Project, type UpdateProject } from '../types/api'
import { amount, ErrorNotice, Field, optional } from './ui'

export default function ProjectForm({ project, assets, onSave, onCancel }: { project?: Project; assets: Asset[]; onSave: (input: CreateProject | UpdateProject) => Promise<void>; onCancel: () => void }) {
  const [name, setName] = useState(project?.name ?? '')
  const [description, setDescription] = useState(project?.description ?? '')
  const [status, setStatus] = useState<EditableProjectStatus>(project?.status === 'archived' ? 'planned' : project?.status ?? 'idea')
  const [priority, setPriority] = useState<Priority>(project?.priority ?? 'normal')
  const [targetDate, setTargetDate] = useState(project?.targetDate ?? '')
  const [estimatedCost, setEstimatedCost] = useState(project?.estimatedCost?.toString() ?? '')
  const [actualCost, setActualCost] = useState(project?.actualCost?.toString() ?? '')
  const [notes, setNotes] = useState(project?.notes ?? '')
  const [assetIds, setAssetIds] = useState<string[]>(project?.assets.map(asset => asset.id) ?? [])
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  function toggle(id: string) { setAssetIds(ids => ids.includes(id) ? ids.filter(item => item !== id) : [...ids, id]) }
  async function submit(event: FormEvent) {
    event.preventDefault()
    if (!name.trim()) { setError('Name is required.'); return }
    const input = { name: name.trim(), description: optional(description), status, priority, targetDate: optional(targetDate), estimatedCost: amount(estimatedCost), actualCost: amount(actualCost), notes: optional(notes), assetIds }
    setBusy(true); setError(null)
    try { await onSave(input) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save project.') } finally { setBusy(false) }
  }
  return <form className="form-grid" onSubmit={submit}><ErrorNotice error={error} />
    <Field label="Name *"><input required value={name} onChange={e => setName(e.target.value)} /></Field>
    <Field label="Status"><select value={status} onChange={e => setStatus(e.target.value as EditableProjectStatus)}>{projectStatuses.map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></Field>
    <Field label="Priority"><select value={priority} onChange={e => setPriority(e.target.value as Priority)}>{priorities.map(value => <option key={value} value={value}>{value}</option>)}</select></Field>
    <Field label="Target date"><input type="date" value={targetDate} onChange={e => setTargetDate(e.target.value)} /></Field>
    <Field label="Estimated cost"><input type="number" min="0" max="9999999999.99" step="0.01" value={estimatedCost} onChange={e => setEstimatedCost(e.target.value)} /></Field>
    <Field label="Actual cost"><input type="number" min="0" max="9999999999.99" step="0.01" value={actualCost} onChange={e => setActualCost(e.target.value)} /></Field>
    <Field label="Description"><textarea rows={3} value={description} onChange={e => setDescription(e.target.value)} /></Field>
    <Field label="Notes"><textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} /></Field>
    <fieldset className="full"><legend>Associated assets</legend><div className="check-list">{assets.length ? assets.map(asset => <label key={asset.id}><input type="checkbox" checked={assetIds.includes(asset.id)} onChange={() => toggle(asset.id)} /><span>{asset.name} <small>({asset.assetType.name})</small></span></label>) : <span className="muted">No assets available.</span>}</div></fieldset>
    <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button disabled={busy}>{busy ? 'Saving…' : 'Save project'}</button></div>
  </form>
}
